# Linear Algebra

In [1]:
import torch

## Scalars

Scalars are the numbers of the everyday mathematics. Scalars are denote by ordinary lower-cased letters (e.g., $x$,$y$ and $z$) and the space of all (continuous) real-valued scalars by $\Bbb{R}$. The scalars are defined in this space in this way $x \in \Bbb{R}$.

Scalars are implemented as tensors that contain only one element


In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## Vectors 

For current purposes, you can think of a vector as a fixed-length array of scalars. As with their code counterparts, we call these scalars the elements of the vector (synonyms include entries and components). When vectors represent examples from real-world datasets, their values hold some real-world significance.

Vectors are implemented as 1st-order tensors. In general, such tensors can have arbitrary lengths, subject to memory limitations

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

- We refer to a vector with a bold lowercase letter as $\mathbf{x}$
- We  refer to an element of a vector using a subscript as $x_2$

$$\mathbf{x} = \begin{bmatrix}x_{0} \\ \vdots \\ x_{n-1}\end{bmatrix},$$

- Here $x_0, \ldots, x_{n-1}$ are elements of the vector. Later on, we will distinguish between such column vectors and row vectors whose elements are stacked horizontally. Recall that we access a tensor’s elements via indexing

In [5]:
x[0], x[2], x[-1], x[-2]

(tensor(0), tensor(2), tensor(2), tensor(1))

To indicate that a vector contains elements, we write $\mathbf{x} \in \Bbb{R}^{n}$ Formally, we call $n$ the dimensionality of the vector.

In [6]:
len(x) , x.shape

(3, torch.Size([3]))

- We use order to refer to the number of axes and dimensionality exclusively to refer to the number of components.

## Matrices

- We denote matrices by bold capital letters as $\mathbf{A}$
- The expresion $\mathbf{A} \in \Bbb{R}^{m \times n}$ indicates a matrix $\mathbf{A}$ contains $m \times n$ real-valued scalars, arranged as $m$ rows and $n$ columns.
- When $m = n$ we say that the matrix is square.
- We can ilustrate any matrix as a table.
- To refer to an individual element we subscript bot the row and column indices $a_{ij}$ element in $\mathbf{A}$'s $i^{th}$ row and $j^{th}$ column

$$\begin{split}\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}.\end{split}$$

- In code, we represent a matrix $\mathbf{A} \in \Bbb{R}^{m \times n}$ by a 2nd order tensor whit shape $(m,n)$
- Matrices are useful for representing datasets. Typically, rows correspond to individual records and columns correspond to distinct attributes.

In [7]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
A.reshape(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [10]:
A.reshape(1,6)

tensor([[0, 1, 2, 3, 4, 5]])

In [11]:
A.reshape(6,1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])

### Transpose

- Sometimes we want to flip the axes. When we exchange a matrix’s rows and columns, the result is called its transpose.
- Formally, we signify a matrix $\mathbf{A}$’s transpose by $\mathbf{A}^{T}$ and if $\mathbf{B} = \mathbf{A}^{T}$, then $b_{ij} = a_{ij}$ for all $i$ and $j$. 
- The transpose of an $m \times n$ matrix is an $n \times m$ matrix:

$$\begin{split}\mathbf{A}^\top =
\begin{bmatrix}
    a_{11} & a_{21} & \dots  & a_{m1} \\
    a_{12} & a_{22} & \dots  & a_{m2} \\
    \vdots & \vdots & \ddots  & \vdots \\
    a_{1n} & a_{2n} & \dots  & a_{mn}
\end{bmatrix}.\end{split}$$

In [12]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

**Symmetric matrices**

Symmetric matrices are the subset of square matrices that are equal to their own transposes: $\mathbf{A} = \mathbf{A}^\top$
. The following matrix is symmetric:

In [15]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## Tensors

## Basic Tensor Properties

## Reduction

## Non-Reduction Sum

## Dot Products

## Matrix-Vector Products

## Matrix-Matrix Multiplication

## Norms